# render.yaml (fixed)
services:
  - type: web
    name: lms-backend
    runtime: docker
    # plan: starter           # optional; you can omit to choose in UI
    rootDir: LMS_Back_End
    dockerfilePath: Dockerfile   # <--- was LMS_Back_End/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: lms-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: lms-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: lms-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: "8080"

  - type: web
    name: lms-frontend
    runtime: static
    rootDir: front-end
    buildCommand: >
      sh -c "npm ci &&
             export VITE_API_URL=https://$BACKEND_HOST &&
             echo Building with VITE_API_URL=$VITE_API_URL &&
             npm run build"
    staticPublishPath: dist
    envVars:
      - key: BACKEND_HOST
        fromService:
          name: lms-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: lms-db
  - databaseName: lms
    user: lms
    plan: free
